const ACTIONS = {
  CONFIG_LOADED: 'CONFIG_LOADED',
  REQUEST_ARTIST: 'REQUEST_ARTIST',
  RECEIVE_ARTIST: 'RECEIVE_ARTIST',
  REQUEST_EVENTS: 'REQUEST_EVENTS',
  RECEIVE_EVENTS: 'RECEIVE_EVENTS',
  GET_DATA_FROM_DB: 'GET_DATA_FROM_DB'
};

export default {
  ...ACTIONS,
};
